# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/busqueda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 527)
        Dialog.setStyleSheet("\n"
"background-color:#D9D9D9;\n"
"\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"border-radius: 15px;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}background-color:rgb(152, 228, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_dia = QtWidgets.QLineEdit(Dialog)
        self.input_dia.setMinimumSize(QtCore.QSize(0, 40))
        self.input_dia.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;\n"
"")
        self.input_dia.setObjectName("input_dia")
        self.verticalLayout.addWidget(self.input_dia)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_hora = QtWidgets.QLineEdit(Dialog)
        self.input_hora.setMinimumSize(QtCore.QSize(0, 40))
        self.input_hora.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;\n"
"")
        self.input_hora.setObjectName("input_hora")
        self.verticalLayout.addWidget(self.input_hora)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_materia = QtWidgets.QLineEdit(Dialog)
        self.input_materia.setMinimumSize(QtCore.QSize(0, 40))
        self.input_materia.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;\n"
"")
        self.input_materia.setObjectName("input_materia")
        self.horizontalLayout_3.addWidget(self.input_materia)
        self.bt_codigoMat = QtWidgets.QPushButton(Dialog)
        self.bt_codigoMat.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_codigoMat.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/baseline-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_codigoMat.setIcon(icon)
        self.bt_codigoMat.setObjectName("bt_codigoMat")
        self.horizontalLayout_3.addWidget(self.bt_codigoMat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_salon = QtWidgets.QLineEdit(Dialog)
        self.input_salon.setMinimumSize(QtCore.QSize(0, 40))
        self.input_salon.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;\n"
"")
        self.input_salon.setObjectName("input_salon")
        self.horizontalLayout_2.addWidget(self.input_salon)
        self.bt_codigoSalon = QtWidgets.QPushButton(Dialog)
        self.bt_codigoSalon.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_codigoSalon.setText("")
        self.bt_codigoSalon.setIcon(icon)
        self.bt_codigoSalon.setObjectName("bt_codigoSalon")
        self.horizontalLayout_2.addWidget(self.bt_codigoSalon)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_profesor = QtWidgets.QLineEdit(Dialog)
        self.input_profesor.setMinimumSize(QtCore.QSize(0, 40))
        self.input_profesor.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;\n"
"")
        self.input_profesor.setObjectName("input_profesor")
        self.horizontalLayout.addWidget(self.input_profesor)
        self.bt_CedulaProf = QtWidgets.QPushButton(Dialog)
        self.bt_CedulaProf.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_CedulaProf.setText("")
        self.bt_CedulaProf.setIcon(icon)
        self.bt_CedulaProf.setObjectName("bt_CedulaProf")
        self.horizontalLayout.addWidget(self.bt_CedulaProf)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boton_guardar = QtWidgets.QPushButton(Dialog)
        self.boton_guardar.setMinimumSize(QtCore.QSize(50, 40))
        self.boton_guardar.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.boton_guardar.setObjectName("boton_guardar")
        self.verticalLayout_2.addWidget(self.boton_guardar)
        self.boton_cancelar = QtWidgets.QPushButton(Dialog)
        self.boton_cancelar.setMinimumSize(QtCore.QSize(50, 40))
        self.boton_cancelar.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.boton_cancelar.setObjectName("boton_cancelar")
        self.verticalLayout_2.addWidget(self.boton_cancelar)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Dia :"))
        self.label_2.setText(_translate("Dialog", "Hora :"))
        self.label_3.setText(_translate("Dialog", "Codigo Materia"))
        self.label_4.setText(_translate("Dialog", "Codigo Salon"))
        self.label_5.setText(_translate("Dialog", "Nombre Profesor"))
        self.boton_guardar.setText(_translate("Dialog", "Guardar"))
        self.boton_cancelar.setText(_translate("Dialog", "Cancelar"))
