# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/busqueda.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(337, 452)
        Dialog.setStyleSheet("background-color:rgb(152, 228, 255);")
        self.bt_codigoMat = QtWidgets.QPushButton(Dialog)
        self.bt_codigoMat.setGeometry(QtCore.QRect(280, 210, 31, 21))
        self.bt_codigoMat.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_codigoMat.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/baseline-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_codigoMat.setIcon(icon)
        self.bt_codigoMat.setObjectName("bt_codigoMat")
        self.bt_codigoSalon = QtWidgets.QPushButton(Dialog)
        self.bt_codigoSalon.setGeometry(QtCore.QRect(280, 280, 31, 21))
        self.bt_codigoSalon.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_codigoSalon.setText("")
        self.bt_codigoSalon.setIcon(icon)
        self.bt_codigoSalon.setObjectName("bt_codigoSalon")
        self.bt_CedulaProf = QtWidgets.QPushButton(Dialog)
        self.bt_CedulaProf.setGeometry(QtCore.QRect(280, 340, 31, 21))
        self.bt_CedulaProf.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.bt_CedulaProf.setText("")
        self.bt_CedulaProf.setIcon(icon)
        self.bt_CedulaProf.setObjectName("bt_CedulaProf")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 370, 261, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boton_guardar = QtWidgets.QPushButton(self.widget)
        self.boton_guardar.setMinimumSize(QtCore.QSize(50, 30))
        self.boton_guardar.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        self.boton_guardar.setObjectName("boton_guardar")
        self.verticalLayout_2.addWidget(self.boton_guardar)
        self.boton_cancelar = QtWidgets.QPushButton(self.widget)
        self.boton_cancelar.setMinimumSize(QtCore.QSize(50, 30))
        self.boton_cancelar.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        self.boton_cancelar.setObjectName("boton_cancelar")
        self.verticalLayout_2.addWidget(self.boton_cancelar)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 261, 321))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_dia = QtWidgets.QLineEdit(self.widget1)
        self.input_dia.setObjectName("input_dia")
        self.verticalLayout.addWidget(self.input_dia)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_hora = QtWidgets.QLineEdit(self.widget1)
        self.input_hora.setObjectName("input_hora")
        self.verticalLayout.addWidget(self.input_hora)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.input_materia = QtWidgets.QLineEdit(self.widget1)
        self.input_materia.setObjectName("input_materia")
        self.verticalLayout.addWidget(self.input_materia)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_salon = QtWidgets.QLineEdit(self.widget1)
        self.input_salon.setObjectName("input_salon")
        self.verticalLayout.addWidget(self.input_salon)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.input_profesor = QtWidgets.QLineEdit(self.widget1)
        self.input_profesor.setObjectName("input_profesor")
        self.verticalLayout.addWidget(self.input_profesor)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.boton_guardar.setText(_translate("Dialog", "Guardar"))
        self.boton_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label.setText(_translate("Dialog", "Dia :"))
        self.label_2.setText(_translate("Dialog", "Hora :"))
        self.label_3.setText(_translate("Dialog", "Codigo Materia"))
        self.label_4.setText(_translate("Dialog", "Codigo Salon"))
        self.label_5.setText(_translate("Dialog", "Nombre Profesor"))
