# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/diasPre.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 275)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 60, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:18px;")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(150, 120, 191, 31))
        self.comboBox.setStyleSheet("border-radius:15px;\n"
"border-color:black;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bt_guardar = QtWidgets.QPushButton(Dialog)
        self.bt_guardar.setGeometry(QtCore.QRect(200, 180, 90, 28))
        self.bt_guardar.setObjectName("bt_guardar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Dias establecidos para el profesor"))
        self.comboBox.setItemText(0, _translate("Dialog", "Lunes"))
        self.comboBox.setItemText(1, _translate("Dialog", "Martes"))
        self.comboBox.setItemText(2, _translate("Dialog", "Miercoles"))
        self.comboBox.setItemText(3, _translate("Dialog", "Jueves"))
        self.comboBox.setItemText(4, _translate("Dialog", "Viernes"))
        self.comboBox.setItemText(5, _translate("Dialog", "Sabado"))
        self.bt_guardar.setText(_translate("Dialog", "Guardar"))
