# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/eliminarhorarioquestion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 134)
        Dialog.setStyleSheet("background-color:rgb(152, 228, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:14px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.bt_eliminar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_eliminar.sizePolicy().hasHeightForWidth())
        self.bt_eliminar.setSizePolicy(sizePolicy)
        self.bt_eliminar.setMinimumSize(QtCore.QSize(0, 30))
        self.bt_eliminar.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.gridLayout.addWidget(self.bt_eliminar, 1, 0, 1, 1)
        self.bt_view = QtWidgets.QPushButton(Dialog)
        self.bt_view.setMinimumSize(QtCore.QSize(0, 30))
        self.bt_view.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_view.setObjectName("bt_view")
        self.gridLayout.addWidget(self.bt_view, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "¿Deseas eliminar el horario \n"
"actual o visualizarlo?"))
        self.bt_eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_view.setText(_translate("Dialog", "Visualizar U Agregar"))
