# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\IUTA -- HORARIOS\ui\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 661, 581))
        self.frame.setStyleSheet("background-color:rgb(152, 228, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(240, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.text = QtWidgets.QLabel(self.frame)
        self.text.setGeometry(QtCore.QRect(150, 90, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setText("")
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.Loginboton = QtWidgets.QPushButton(self.frame)
        self.Loginboton.setGeometry(QtCore.QRect(30, 160, 141, 51))
        self.Loginboton.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/calendar3 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Loginboton.setIcon(icon)
        self.Loginboton.setIconSize(QtCore.QSize(20, 20))
        self.Loginboton.setObjectName("Loginboton")
        self.bt_teachers = QtWidgets.QPushButton(self.frame)
        self.bt_teachers.setGeometry(QtCore.QRect(30, 220, 141, 51))
        self.bt_teachers.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/chalkboard-teacher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_teachers.setIcon(icon1)
        self.bt_teachers.setIconSize(QtCore.QSize(20, 20))
        self.bt_teachers.setObjectName("bt_teachers")
        self.Loginboton_3 = QtWidgets.QPushButton(self.frame)
        self.Loginboton_3.setGeometry(QtCore.QRect(30, 280, 141, 51))
        self.Loginboton_3.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/round-class.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Loginboton_3.setIcon(icon2)
        self.Loginboton_3.setIconSize(QtCore.QSize(20, 20))
        self.Loginboton_3.setObjectName("Loginboton_3")
        self.Loginboton_4 = QtWidgets.QPushButton(self.frame)
        self.Loginboton_4.setGeometry(QtCore.QRect(30, 350, 141, 51))
        self.Loginboton_4.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/university.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Loginboton_4.setIcon(icon3)
        self.Loginboton_4.setIconSize(QtCore.QSize(20, 20))
        self.Loginboton_4.setObjectName("Loginboton_4")
        self.bt_carreras = QtWidgets.QPushButton(self.frame)
        self.bt_carreras.setGeometry(QtCore.QRect(30, 420, 141, 51))
        self.bt_carreras.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/system-sum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_carreras.setIcon(icon4)
        self.bt_carreras.setIconSize(QtCore.QSize(20, 20))
        self.bt_carreras.setObjectName("bt_carreras")
        self.bt_salir = QtWidgets.QPushButton(self.frame)
        self.bt_salir.setGeometry(QtCore.QRect(560, 30, 75, 31))
        self.bt_salir.setStyleSheet("background-color:red;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;")
        self.bt_salir.setObjectName("bt_salir")
        self.bt_close = QtWidgets.QPushButton(self.frame)
        self.bt_close.setGeometry(QtCore.QRect(40, 30, 101, 31))
        self.bt_close.setStyleSheet("background-color:red;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;")
        self.bt_close.setObjectName("bt_close")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(270, 200, 381, 231))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/iutaImg.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.bt_users = QtWidgets.QPushButton(self.frame)
        self.bt_users.setGeometry(QtCore.QRect(490, 500, 141, 51))
        self.bt_users.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\IUTA -- HORARIOS\\ui\\imagenes/user-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_users.setIcon(icon5)
        self.bt_users.setIconSize(QtCore.QSize(20, 20))
        self.bt_users.setObjectName("bt_users")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MENU PRINCIPAL"))
        self.Loginboton.setText(_translate("MainWindow", "Horarios"))
        self.bt_teachers.setText(_translate("MainWindow", "Profesores"))
        self.Loginboton_3.setText(_translate("MainWindow", "Materias"))
        self.Loginboton_4.setText(_translate("MainWindow", "Sedes"))
        self.bt_carreras.setText(_translate("MainWindow", "Carreras"))
        self.bt_salir.setText(_translate("MainWindow", "SALIR"))
        self.bt_close.setText(_translate("MainWindow", "Cerrar Sesion"))
        self.bt_users.setText(_translate("MainWindow", "Usuarios"))
