# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/modalidadBusqueda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color:rgb(152, 228, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 20, 241, 81))
        self.label.setStyleSheet("font: 57 18pt \"Likhan\";")
        self.label.setObjectName("label")
        self.bt_busqueda = QtWidgets.QPushButton(Dialog)
        self.bt_busqueda.setGeometry(QtCore.QRect(40, 190, 151, 41))
        self.bt_busqueda.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        self.bt_busqueda.setObjectName("bt_busqueda")
        self.combo_box = QtWidgets.QComboBox(Dialog)
        self.combo_box.setGeometry(QtCore.QRect(110, 110, 181, 31))
        self.combo_box.setObjectName("combo_box")
        self.bt_crear = QtWidgets.QPushButton(Dialog)
        self.bt_crear.setGeometry(QtCore.QRect(240, 190, 151, 41))
        self.bt_crear.setStyleSheet("border-radius:15px;\n"
"color:white;\n"
"font-size:15px;\n"
"background-color: rgb(104, 126, 255);")
        self.bt_crear.setObjectName("bt_crear")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Seleccionar Modalidad"))
        self.bt_busqueda.setText(_translate("Dialog", "Realizar Busqueda"))
        self.bt_crear.setText(_translate("Dialog", "Crear"))
