# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/moduloProfesor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"QFrame{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"\n"
"QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;\n"
"background-color:#d9d9d9;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 782, 18))
        font = QtGui.QFont()
        font.setFamily("3270 Nerd Font Mono")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(48, 30, 711, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_volver = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_volver.setMinimumSize(QtCore.QSize(80, 40))
        self.bt_volver.setObjectName("bt_volver")
        self.horizontalLayout.addWidget(self.bt_volver)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ln_profesor = QtWidgets.QLineEdit(self.layoutWidget)
        self.ln_profesor.setMinimumSize(QtCore.QSize(100, 40))
        self.ln_profesor.setObjectName("ln_profesor")
        self.horizontalLayout.addWidget(self.ln_profesor)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.bt_profesor = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_profesor.setMinimumSize(QtCore.QSize(80, 40))
        self.bt_profesor.setObjectName("bt_profesor")
        self.horizontalLayout_2.addWidget(self.bt_profesor)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 80, 791, 471))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"                background-color: transparent;\n"
"                border: 1px solid black;\n"
"                border-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section {\n"
"                background-color: #253b59;\n"
"                color: #fff;\n"
"                border-bottom: 2px solid white;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section:first {\n"
"                border-top-left-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section:last {\n"
"                border-top-right-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QTableCornerButton::section {\n"
"                background-color: #63b6bf;\n"
"                border-top-left-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget::item {\n"
"                background-color: #63b6bf;\n"
"                color: #111626;\n"
"                border-bottom: 1px solid black;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTableWidget::item:selected {\n"
"                background-color: #b6ecf2;\n"
"                color: #111626;\n"
"            }")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.bt_clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.bt_clear.setMinimumSize(QtCore.QSize(80, 40))
        self.bt_clear.setObjectName("bt_clear")
        self.verticalLayout.addWidget(self.bt_clear)
        self.bt_guardarSeleccion = QtWidgets.QPushButton(self.layoutWidget1)
        self.bt_guardarSeleccion.setMinimumSize(QtCore.QSize(80, 40))
        self.bt_guardarSeleccion.setObjectName("bt_guardarSeleccion")
        self.verticalLayout.addWidget(self.bt_guardarSeleccion)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Mododulos para Profesor"))
        self.bt_volver.setText(_translate("MainWindow", "Volver"))
        self.label.setText(_translate("MainWindow", "Profesor"))
        self.bt_profesor.setText(_translate("MainWindow", "buscar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Horas"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miercoles"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sabado"))
        self.bt_clear.setText(_translate("MainWindow", "Limpiar"))
        self.bt_guardarSeleccion.setText(_translate("MainWindow", "Guardar"))
