# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/plantilla_menu_de_horarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 630)
        MainWindow.setStyleSheet("\n"
"QMainWindow{\n"
"background-color:#D9D9D9;\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_back = QtWidgets.QPushButton(self.centralwidget)
        self.bt_back.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_back.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_back.setObjectName("bt_back")
        self.horizontalLayout.addWidget(self.bt_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_salir = QtWidgets.QPushButton(self.centralwidget)
        self.bt_salir.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_salir.setObjectName("bt_salir")
        self.horizontalLayout.addWidget(self.bt_salir)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    background-color: lightgray;\n"
"    border: 1px solid darkgray;\n"
"    font: 75 12pt \"Arial\";\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    background-color: #00007f;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background-color: #55aaff;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: black;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 729, 372))
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_55 = QtWidgets.QLabel(self.page)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_5.addWidget(self.label_55)
        self.ln_disponibilidad_aula = QtWidgets.QLineEdit(self.page)
        self.ln_disponibilidad_aula.setMinimumSize(QtCore.QSize(0, 40))
        self.ln_disponibilidad_aula.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_disponibilidad_aula.setReadOnly(True)
        self.ln_disponibilidad_aula.setObjectName("ln_disponibilidad_aula")
        self.horizontalLayout_5.addWidget(self.ln_disponibilidad_aula)
        self.bt_buscar = QtWidgets.QPushButton(self.page)
        self.bt_buscar.setStyleSheet("border:none;")
        self.bt_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/baseline-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_buscar.setIcon(icon)
        self.bt_buscar.setObjectName("bt_buscar")
        self.horizontalLayout_5.addWidget(self.bt_buscar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tableWidget_aulas = QtWidgets.QTableWidget(self.page)
        self.tableWidget_aulas.setObjectName("tableWidget_aulas")
        self.tableWidget_aulas.setColumnCount(7)
        self.tableWidget_aulas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_aulas.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.tableWidget_aulas)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.bt_buscarAula = QtWidgets.QPushButton(self.page)
        self.bt_buscarAula.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_buscarAula.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_buscarAula.setObjectName("bt_buscarAula")
        self.horizontalLayout_6.addWidget(self.bt_buscarAula)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/university.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon1, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 729, 372))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.label_57 = QtWidgets.QLabel(self.page_2)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_11.addWidget(self.label_57)
        self.ln_disponibilidad_profesores = QtWidgets.QLineEdit(self.page_2)
        self.ln_disponibilidad_profesores.setMinimumSize(QtCore.QSize(0, 40))
        self.ln_disponibilidad_profesores.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.ln_disponibilidad_profesores.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_disponibilidad_profesores.setReadOnly(True)
        self.ln_disponibilidad_profesores.setObjectName("ln_disponibilidad_profesores")
        self.horizontalLayout_11.addWidget(self.ln_disponibilidad_profesores)
        self.bt_profesor = QtWidgets.QPushButton(self.page_2)
        self.bt_profesor.setText("")
        self.bt_profesor.setIcon(icon)
        self.bt_profesor.setObjectName("bt_profesor")
        self.horizontalLayout_11.addWidget(self.bt_profesor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.tableWidget_profesores = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_profesores.setObjectName("tableWidget_profesores")
        self.tableWidget_profesores.setColumnCount(7)
        self.tableWidget_profesores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_profesores.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.tableWidget_profesores)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.bt_imprimirProfesor = QtWidgets.QPushButton(self.page_2)
        self.bt_imprimirProfesor.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_imprimirProfesor.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_imprimirProfesor.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_imprimirProfesor.setObjectName("bt_imprimirProfesor")
        self.horizontalLayout_4.addWidget(self.bt_imprimirProfesor)
        self.bt_buscarProf = QtWidgets.QPushButton(self.page_2)
        self.bt_buscarProf.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_buscarProf.setMaximumSize(QtCore.QSize(100, 40))
        self.bt_buscarProf.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_buscarProf.setObjectName("bt_buscarProf")
        self.horizontalLayout_4.addWidget(self.bt_buscarProf)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/adduser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 729, 372))
        self.page_3.setObjectName("page_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_73 = QtWidgets.QLabel(self.page_3)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_20.addWidget(self.label_73)
        self.ln_disponibilidad_carrera = QtWidgets.QLineEdit(self.page_3)
        self.ln_disponibilidad_carrera.setMinimumSize(QtCore.QSize(100, 40))
        self.ln_disponibilidad_carrera.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_disponibilidad_carrera.setReadOnly(True)
        self.ln_disponibilidad_carrera.setObjectName("ln_disponibilidad_carrera")
        self.horizontalLayout_20.addWidget(self.ln_disponibilidad_carrera)
        self.bt_carrerabuscar = QtWidgets.QPushButton(self.page_3)
        self.bt_carrerabuscar.setStyleSheet("border:none;")
        self.bt_carrerabuscar.setText("")
        self.bt_carrerabuscar.setIcon(icon)
        self.bt_carrerabuscar.setObjectName("bt_carrerabuscar")
        self.horizontalLayout_20.addWidget(self.bt_carrerabuscar)
        self.ln_disponibilidad_seccion = QtWidgets.QLineEdit(self.page_3)
        self.ln_disponibilidad_seccion.setMinimumSize(QtCore.QSize(100, 40))
        self.ln_disponibilidad_seccion.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_disponibilidad_seccion.setReadOnly(True)
        self.ln_disponibilidad_seccion.setObjectName("ln_disponibilidad_seccion")
        self.horizontalLayout_20.addWidget(self.ln_disponibilidad_seccion)
        self.bt_seccionbuscar = QtWidgets.QPushButton(self.page_3)
        self.bt_seccionbuscar.setStyleSheet("border:none;")
        self.bt_seccionbuscar.setText("")
        self.bt_seccionbuscar.setIcon(icon)
        self.bt_seccionbuscar.setObjectName("bt_seccionbuscar")
        self.horizontalLayout_20.addWidget(self.bt_seccionbuscar)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_20)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget_seccion = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_seccion.setObjectName("tableWidget_seccion")
        self.tableWidget_seccion.setColumnCount(7)
        self.tableWidget_seccion.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_seccion.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget_seccion)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.bt_sesion = QtWidgets.QPushButton(self.page_3)
        self.bt_sesion.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_sesion.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;")
        self.bt_sesion.setObjectName("bt_sesion")
        self.horizontalLayout_7.addWidget(self.bt_sesion)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/users-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon3, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.bt_delete = QtWidgets.QPushButton(self.centralwidget)
        self.bt_delete.setMinimumSize(QtCore.QSize(160, 61))
        self.bt_delete.setMaximumSize(QtCore.QSize(160, 61))
        self.bt_delete.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;\n"
"font-size:15px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_delete.setIcon(icon4)
        self.bt_delete.setIconSize(QtCore.QSize(20, 20))
        self.bt_delete.setObjectName("bt_delete")
        self.horizontalLayout_2.addWidget(self.bt_delete)
        self.bt_crear = QtWidgets.QPushButton(self.centralwidget)
        self.bt_crear.setMinimumSize(QtCore.QSize(160, 61))
        self.bt_crear.setMaximumSize(QtCore.QSize(160, 61))
        self.bt_crear.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}\n"
"font-size:15px;\n"
"font-size:15px;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/calendar3 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_crear.setIcon(icon5)
        self.bt_crear.setIconSize(QtCore.QSize(20, 20))
        self.bt_crear.setObjectName("bt_crear")
        self.horizontalLayout_2.addWidget(self.bt_crear)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_back.setText(_translate("MainWindow", "Volver "))
        self.label.setText(_translate("MainWindow", "nombre de la modalidad"))
        self.bt_salir.setText(_translate("MainWindow", "Salir"))
        self.label_55.setText(_translate("MainWindow", "Verificar disponibilidad"))
        self.ln_disponibilidad_aula.setPlaceholderText(_translate("MainWindow", "Aula"))
        item = self.tableWidget_aulas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget_aulas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget_aulas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget_aulas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miercoles"))
        item = self.tableWidget_aulas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget_aulas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget_aulas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sabado"))
        self.bt_buscarAula.setText(_translate("MainWindow", "Buscar"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Disponibilidad Aulas"))
        self.label_57.setText(_translate("MainWindow", "Verificar disponibilidad"))
        self.ln_disponibilidad_profesores.setPlaceholderText(_translate("MainWindow", "Profesor"))
        item = self.tableWidget_profesores.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget_profesores.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget_profesores.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget_profesores.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miercoles"))
        item = self.tableWidget_profesores.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget_profesores.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget_profesores.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sabado"))
        self.bt_imprimirProfesor.setText(_translate("MainWindow", "Imprimir"))
        self.bt_buscarProf.setText(_translate("MainWindow", "Buscar"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Disponibilidad Profesores"))
        self.label_73.setText(_translate("MainWindow", "Verificar disponibilidad"))
        self.ln_disponibilidad_carrera.setPlaceholderText(_translate("MainWindow", "Nivel"))
        self.ln_disponibilidad_seccion.setPlaceholderText(_translate("MainWindow", "Seccion"))
        item = self.tableWidget_seccion.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget_seccion.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lunes"))
        item = self.tableWidget_seccion.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Martes"))
        item = self.tableWidget_seccion.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miercoles"))
        item = self.tableWidget_seccion.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jueves"))
        item = self.tableWidget_seccion.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Viernes"))
        item = self.tableWidget_seccion.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sabado"))
        self.bt_sesion.setText(_translate("MainWindow", "Buscar"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Disponibilidad Seccion"))
        self.bt_delete.setText(_translate("MainWindow", "Eliminar Horarios"))
        self.bt_crear.setText(_translate("MainWindow", "Ver y Crear Horario"))
