# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/teachers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 506)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color:#d9d9d9;\n"
"\n"
"QTableWidget {border: 1px solid black;border-radius: 10px;}\n"
"QTableWidget::item {background-color:#b6ecf2;color: #fff;border-bottom: 1px solid black;padding: 5px;}\n"
"QTableWidget::item:selected {background-color: #b6ecf2;color: #111626;}\n"
"QTableWidget::horizontalHeaderItem {background-color: #63b6bf;color: #111626;border-bottom: 2px solid white;\n"
"  /* Separación entre el encabezado y el cuerpo */\n"
"border-top-left-radius: 10px;border-top-right-radius: 10px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:#D9D9D9;\n"
"\n"
"}\n"
"QLineEdit{\n"
"background-color: #7E94Bf;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"color:#111626;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_back = QtWidgets.QPushButton(self.frame)
        self.bt_back.setMinimumSize(QtCore.QSize(90, 40))
        self.bt_back.setMaximumSize(QtCore.QSize(90, 40))
        self.bt_back.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_back.setObjectName("bt_back")
        self.horizontalLayout.addWidget(self.bt_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_salir = QtWidgets.QPushButton(self.frame)
        self.bt_salir.setMinimumSize(QtCore.QSize(90, 40))
        self.bt_salir.setMaximumSize(QtCore.QSize(90, 40))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_salir.setObjectName("bt_salir")
        self.horizontalLayout.addWidget(self.bt_salir)
        self.verticalLayout_19.addLayout(self.horizontalLayout)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#233559;\n"
"border-radius:40px;\n"
"}\n"
"QPushButton{\n"
"background-color:#233559;\n"
"color:#FFF;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color: #637aa6 ;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setStyleSheet("background-color:#d9d9d9;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.bt_agg = QtWidgets.QPushButton(self.frame_2)
        self.bt_agg.setMinimumSize(QtCore.QSize(120, 40))
        self.bt_agg.setMaximumSize(QtCore.QSize(120, 40))
        self.bt_agg.setStyleSheet("font-size:15px;\n"
"")
        self.bt_agg.setIconSize(QtCore.QSize(20, 20))
        self.bt_agg.setObjectName("bt_agg")
        self.verticalLayout_9.addWidget(self.bt_agg)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.bt_edit = QtWidgets.QPushButton(self.frame_2)
        self.bt_edit.setMinimumSize(QtCore.QSize(120, 40))
        self.bt_edit.setMaximumSize(QtCore.QSize(120, 40))
        self.bt_edit.setStyleSheet("font-size:15px;\n"
"")
        self.bt_edit.setIconSize(QtCore.QSize(20, 20))
        self.bt_edit.setObjectName("bt_edit")
        self.verticalLayout_9.addWidget(self.bt_edit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.bt_view = QtWidgets.QPushButton(self.frame_2)
        self.bt_view.setMinimumSize(QtCore.QSize(120, 40))
        self.bt_view.setMaximumSize(QtCore.QSize(120, 40))
        self.bt_view.setStyleSheet("font-size:15px;\n"
"")
        self.bt_view.setIconSize(QtCore.QSize(20, 20))
        self.bt_view.setObjectName("bt_view")
        self.verticalLayout_9.addWidget(self.bt_view)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setStyleSheet("background-color:#d9d9d9;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_17.addWidget(self.frame_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_agg = QtWidgets.QWidget()
        self.page_agg.setObjectName("page_agg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_agg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size:15px;\n"
"color:#111626;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.txt_name = QtWidgets.QLineEdit(self.page_agg)
        self.txt_name.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_name.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_name.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_name.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_name.setObjectName("txt_name")
        self.horizontalLayout_6.addWidget(self.txt_name)
        self.horizontalLayout_49.addLayout(self.horizontalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_49)
        spacerItem9 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size:15px;\n"
"color:#111626;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.txt_apell = QtWidgets.QLineEdit(self.page_agg)
        self.txt_apell.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_apell.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_apell.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_apell.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_apell.setObjectName("txt_apell")
        self.horizontalLayout_5.addWidget(self.txt_apell)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_48)
        spacerItem12 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font-size:15px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.txt_cedula = QtWidgets.QLineEdit(self.page_agg)
        self.txt_cedula.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_cedula.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_cedula.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_cedula.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cedula.setObjectName("txt_cedula")
        self.horizontalLayout_4.addWidget(self.txt_cedula)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        spacerItem15 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font-size:15px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.txt_telefono = QtWidgets.QLineEdit(self.page_agg)
        self.txt_telefono.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_telefono.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_telefono.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_telefono.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_telefono.setObjectName("txt_telefono")
        self.horizontalLayout_3.addWidget(self.txt_telefono)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_3)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        spacerItem18 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font-size:15px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.txt_mail = QtWidgets.QLineEdit(self.page_agg)
        self.txt_mail.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_mail.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_mail.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_mail.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_mail.setObjectName("txt_mail")
        self.horizontalLayout_7.addWidget(self.txt_mail)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.horizontalLayout_50)
        spacerItem21 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem21)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.page_agg)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-size:15px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.txt_profesion = QtWidgets.QLineEdit(self.page_agg)
        self.txt_profesion.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_profesion.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_profesion.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_profesion.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_profesion.setObjectName("txt_profesion")
        self.horizontalLayout_2.addWidget(self.txt_profesion)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_2)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem23)
        self.verticalLayout.addLayout(self.horizontalLayout_51)
        spacerItem24 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem24)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem25)
        self.bt_agg_2 = QtWidgets.QPushButton(self.page_agg)
        self.bt_agg_2.setMinimumSize(QtCore.QSize(120, 40))
        self.bt_agg_2.setMaximumSize(QtCore.QSize(120, 40))
        self.bt_agg_2.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_agg_2.setIconSize(QtCore.QSize(20, 20))
        self.bt_agg_2.setObjectName("bt_agg_2")
        self.horizontalLayout_52.addWidget(self.bt_agg_2)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem26)
        self.verticalLayout.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_54.addLayout(self.verticalLayout)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem27)
        self.verticalLayout_2.addLayout(self.horizontalLayout_54)
        self.stackedWidget.addWidget(self.page_agg)
        self.page_edit = QtWidgets.QWidget()
        self.page_edit.setObjectName("page_edit")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_edit)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem28)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.ln_busqueda = QtWidgets.QLineEdit(self.page_edit)
        self.ln_busqueda.setMinimumSize(QtCore.QSize(0, 40))
        self.ln_busqueda.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ln_busqueda.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(128, 179, 255);\n"
"border-radius:15px;")
        self.ln_busqueda.setObjectName("ln_busqueda")
        self.horizontalLayout_8.addWidget(self.ln_busqueda)
        self.bt_search = QtWidgets.QPushButton(self.page_edit)
        self.bt_search.setStyleSheet("border:none;")
        self.bt_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/IUTA----HORARIOS/ui/imagenes/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_search.setIcon(icon)
        self.bt_search.setIconSize(QtCore.QSize(20, 20))
        self.bt_search.setObjectName("bt_search")
        self.horizontalLayout_8.addWidget(self.bt_search)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem31 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem31)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-size:15px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem32)
        self.txt_name_2 = QtWidgets.QLineEdit(self.page_edit)
        self.txt_name_2.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_name_2.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_name_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_name_2.setObjectName("txt_name_2")
        self.horizontalLayout_12.addWidget(self.txt_name_2)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_12)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem33)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        spacerItem34 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem34)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font-size:15px;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem35)
        self.txt_apell_2 = QtWidgets.QLineEdit(self.page_edit)
        self.txt_apell_2.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_apell_2.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_apell_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_apell_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_apell_2.setObjectName("txt_apell_2")
        self.horizontalLayout_11.addWidget(self.txt_apell_2)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_11)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem36)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        spacerItem37 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem37)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font-size:15px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem38)
        self.txt_cedula_2 = QtWidgets.QLineEdit(self.page_edit)
        self.txt_cedula_2.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_cedula_2.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_cedula_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_cedula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cedula_2.setReadOnly(True)
        self.txt_cedula_2.setObjectName("txt_cedula_2")
        self.horizontalLayout_10.addWidget(self.txt_cedula_2)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_10)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem39)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        spacerItem40 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem40)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font-size:15px;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem41)
        self.txt_telefono_2 = QtWidgets.QLineEdit(self.page_edit)
        self.txt_telefono_2.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_telefono_2.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_telefono_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_telefono_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_telefono_2.setObjectName("txt_telefono_2")
        self.horizontalLayout_9.addWidget(self.txt_telefono_2)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_9)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem42)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        spacerItem43 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem43)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font-size:15px;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem44)
        self.txt_correo = QtWidgets.QLineEdit(self.page_edit)
        self.txt_correo.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_correo.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_correo.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_correo.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_correo.setObjectName("txt_correo")
        self.horizontalLayout_13.addWidget(self.txt_correo)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_13)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        spacerItem46 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem46)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.page_edit)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-size:15px;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem47)
        self.txt_titulos = QtWidgets.QLineEdit(self.page_edit)
        self.txt_titulos.setMinimumSize(QtCore.QSize(200, 30))
        self.txt_titulos.setMaximumSize(QtCore.QSize(200, 30))
        self.txt_titulos.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(128, 179, 255);\n"
"border-right:2px solid rgb(128, 179, 255);\n"
"border-radius:10px;\n"
"font-size:14px;")
        self.txt_titulos.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_titulos.setObjectName("txt_titulos")
        self.horizontalLayout_14.addWidget(self.txt_titulos)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_14)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem48)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        spacerItem49 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem49)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem50)
        self.bt_edit_2 = QtWidgets.QPushButton(self.page_edit)
        self.bt_edit_2.setMinimumSize(QtCore.QSize(90, 40))
        self.bt_edit_2.setMaximumSize(QtCore.QSize(90, 40))
        self.bt_edit_2.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_edit_2.setIconSize(QtCore.QSize(20, 20))
        self.bt_edit_2.setObjectName("bt_edit_2")
        self.horizontalLayout_15.addWidget(self.bt_edit_2)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem51)
        self.bt_delete = QtWidgets.QPushButton(self.page_edit)
        self.bt_delete.setMinimumSize(QtCore.QSize(90, 40))
        self.bt_delete.setMaximumSize(QtCore.QSize(90, 40))
        self.bt_delete.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_delete.setIconSize(QtCore.QSize(20, 20))
        self.bt_delete.setObjectName("bt_delete")
        self.horizontalLayout_15.addWidget(self.bt_delete)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem52)
        self.bt_clear = QtWidgets.QPushButton(self.page_edit)
        self.bt_clear.setMinimumSize(QtCore.QSize(90, 40))
        self.bt_clear.setMaximumSize(QtCore.QSize(90, 40))
        self.bt_clear.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_clear.setIconSize(QtCore.QSize(20, 20))
        self.bt_clear.setObjectName("bt_clear")
        self.horizontalLayout_15.addWidget(self.bt_clear)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem53)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_45.addLayout(self.verticalLayout_3)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem54)
        self.verticalLayout_18.addLayout(self.horizontalLayout_45)
        self.stackedWidget.addWidget(self.page_edit)
        self.page_view = QtWidgets.QWidget()
        self.page_view.setObjectName("page_view")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_view)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.page_view)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.tableWidget = QtWidgets.QTableWidget(self.page_view)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"                background-color: transparent;\n"
"                border: 1px solid black;\n"
"                border-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section {\n"
"                background-color: #253b59;\n"
"                color: #fff;\n"
"                border-bottom: 2px solid white;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section:first {\n"
"                border-top-left-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QHeaderView::section:last {\n"
"                border-top-right-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget QTableCornerButton::section {\n"
"                background-color: #63b6bf;\n"
"                border-top-left-radius: 10px;\n"
"            }\n"
"\n"
"            QTableWidget::item {\n"
"                background-color: #63b6bf;\n"
"                color: #111626;\n"
"                border-bottom: 1px solid black;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTableWidget::item:selected {\n"
"                background-color: #b6ecf2;\n"
"                color: #111626;\n"
"            }")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem55)
        self.bt_act = QtWidgets.QPushButton(self.page_view)
        self.bt_act.setMinimumSize(QtCore.QSize(120, 40))
        self.bt_act.setMaximumSize(QtCore.QSize(120, 40))
        self.bt_act.setStyleSheet("QPushButton{\n"
"background-color:#253b59;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton::Hover{\n"
"background-color:#637aa6;\n"
"}")
        self.bt_act.setIconSize(QtCore.QSize(20, 20))
        self.bt_act.setObjectName("bt_act")
        self.horizontalLayout_16.addWidget(self.bt_act)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_view)
        self.horizontalLayout_17.addWidget(self.stackedWidget)
        self.verticalLayout_19.addLayout(self.horizontalLayout_17)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.verticalLayout_12.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Profesores"))
        self.bt_back.setText(_translate("MainWindow", "Volver"))
        self.bt_salir.setText(_translate("MainWindow", "SALIR"))
        self.bt_agg.setText(_translate("MainWindow", "Agregar "))
        self.bt_edit.setText(_translate("MainWindow", "Editar"))
        self.bt_view.setText(_translate("MainWindow", "Visualizar"))
        self.label_2.setText(_translate("MainWindow", "AGREGAR"))
        self.label_5.setText(_translate("MainWindow", "Nombres   "))
        self.label_6.setText(_translate("MainWindow", "Apellidos   "))
        self.label_7.setText(_translate("MainWindow", "C.I              "))
        self.label_11.setText(_translate("MainWindow", "Telefono   "))
        self.label_12.setText(_translate("MainWindow", "Correo       "))
        self.label_13.setText(_translate("MainWindow", "Titulos       "))
        self.bt_agg_2.setText(_translate("MainWindow", "Agregar "))
        self.label_3.setText(_translate("MainWindow", "EDITAR"))
        self.label_9.setText(_translate("MainWindow", "Nombres    "))
        self.label_10.setText(_translate("MainWindow", "Apellidos    "))
        self.label_8.setText(_translate("MainWindow", "C.I               "))
        self.label_16.setText(_translate("MainWindow", "Telefono    "))
        self.label_14.setText(_translate("MainWindow", "Correo       "))
        self.label_15.setText(_translate("MainWindow", "Titulos       "))
        self.bt_edit_2.setText(_translate("MainWindow", "Modificar"))
        self.bt_delete.setText(_translate("MainWindow", "Eliminar"))
        self.bt_clear.setText(_translate("MainWindow", "Limpiar"))
        self.label_4.setText(_translate("MainWindow", "VISUALIZAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Correo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Profesión"))
        self.bt_act.setText(_translate("MainWindow", "Actualizar"))
